# installing java to base docker from amazon 
#https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/java/openjdk-8/Dockerfile
#https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/docker/1.12.1/Dockerfile
version: 0.2

env:
  variables:      
      AWS_ACCOUNT_ID : "776213096610"      
      BUCKET_NAME : "rexconnect_ui_v2"
      DISTRIBUTION_ID : "E2T49UIMCV01GK" 
      BUILD_ENV : "development" 
      
phases:
  install:
    runtime-versions:
      docker: 18
    commands:      
      # - command
  pre_build:
    commands:
        - echo Logging in to Amazon ECR...        
      # - command
      # - command
  build:
    commands:
        - echo Build started on `date`
        - printenv 
        - npm install          
        #- npm run build $BUILD_ENV
        - npm run build -- --prod --aot=false --build-optimizer=false --configuration $BUILD_ENV
        #- npm run build 
        - cd dist/fp
        - ls -al 
        - aws s3 sync . s3://$BUCKET_NAME --delete  
        - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'